# .github/workflows/test.yml

name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies with pipenv
        run: |
          pip install pipenv
          pipenv install --deploy --dev
          pipenv install pubnub
          pipenv install unittest


      - run: pipenv run mypy
      - run: pipenv run unnittest -m /Backend/test/Analytics_Test.py
      - run: pipenv run unnittest -m /Backend/test/Cloud_Test.py
      - run: pipenv run unnittest -m /Backend/test/Database_Test.py
      - run: pipenv run unnittest -m /Backend/test/Stock_Test.py