# .github/workflows/test.yml

name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python and run tests
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - run: pip install pubnub
      - run: python -m unittest  Analytics_Test.py
      - run: python -m unittest  Cloud_Test.py
      - run: python -m unittest  Database_Test.py
      - run: python -m unittest  Stock_Test.py
